# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BuildingACR
                                 A QGIS plugin
 Links UMEP with CONTAM for building airflow calculations.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-22
        copyright            : (C) 2026 by Yasemin Usta; Xuan Zhou
        email                : yasemin.usta@polito.it; xuan.zhou@polito.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BuildingACR class from file BuildingACR.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .building_acr import BuildingACR
    return BuildingACR(iface)
